In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import f1_score, accuracy_score, precision_recall_curve, precision_score, recall_score,  confusion_matrix

In [56]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
#Load the data
pd.set_option("display.max_columns",None) 
data = pd.read_csv(r"C:\Users\91892\OneDrive\Documents\CCDP_docs\UCI_Credit_Card.csv")
print("Shape of the data", data.shape)
data.head(5)

Shape of the data (30000, 25)


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
0     -2     -2     3913.0     3102.0      689.0        0.0        0.0   
1      0      2     2682.0     1725.0     2682.0     3272.0     3455.0   
2      0      0    29239.0    14027.0    13559.0    14331.0    14948.0   
3      0      0    46990.0    48233.0    49291.0    28314.0    28959.0   
4      0      0     8617.0     5670.0    35835.0    20940.0    19146.0   

   BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0        0.0       0.0     689.0       0.0       0.0       0.0       0.0   
1     3261.0       0.0    1000.0    1000.0    1000.0       0.0    2000.0   
2    15549.0    1518.0    1500.0    1000.0    1000.0    1000.0    5000.0   
3    29547.0    2000.0    2019.0    1200.0    1100.0    1069.0    1000.0   
4    19131.0    2000.0   36681.0   10000.0    9000.0     689.0     679.0   

   default.payment.next.month  
0                           1  
1                           1  
2                           0  
3                           0  
4                           0

In [3]:
data.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [4]:
data.describe()

ID       LIMIT_BAL           SEX     EDUCATION      MARRIAGE  \
count  30000.000000    30000.000000  30000.000000  30000.000000  30000.000000   
mean   15000.500000   167484.322667      1.603733      1.853133      1.551867   
std     8660.398374   129747.661567      0.489129      0.790349      0.521970   
min        1.000000    10000.000000      1.000000      0.000000      0.000000   
25%     7500.750000    50000.000000      1.000000      1.000000      1.000000   
50%    15000.500000   140000.000000      2.000000      2.000000      2.000000   
75%    22500.250000   240000.000000      2.000000      2.000000      2.000000   
max    30000.000000  1000000.000000      2.000000      6.000000      3.000000   

                AGE         PAY_0         PAY_2         PAY_3         PAY_4  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean      35.485500     -0.016700     -0.133767     -0.166200     -0.220667   
std        9.217904      1.123802      1.197186      1.196868      1.169139   
min       21.000000     -2.000000     -2.000000     -2.000000     -2.000000   
25%       28.000000     -1.000000     -1.000000     -1.000000     -1.000000   
50%       34.000000      0.000000      0.000000      0.000000      0.000000   
75%       41.000000      0.000000      0.000000      0.000000      0.000000   
max       79.000000      8.000000      8.000000      8.000000      8.000000   

              PAY_5         PAY_6      BILL_AMT1      BILL_AMT2     BILL_AMT3  \
count  30000.000000  30000.000000   30000.000000   30000.000000  3.000000e+04   
mean      -0.266200     -0.291100   51223.330900   49179.075167  4.701315e+04   
std        1.133187      1.149988   73635.860576   71173.768783  6.934939e+04   
min       -2.000000     -2.000000 -165580.000000  -69777.000000 -1.572640e+05   
25%       -1.000000     -1.000000    3558.750000    2984.750000  2.666250e+03   
50%        0.000000      0.000000   22381.500000   21200.000000  2.008850e+04   
75%        0.000000      0.000000   67091.000000   64006.250000  6.016475e+04   
max        8.000000      8.000000  964511.000000  983931.000000  1.664089e+06   

           BILL_AMT4      BILL_AMT5      BILL_AMT6       PAY_AMT1  \
count   30000.000000   30000.000000   30000.000000   30000.000000   
mean    43262.948967   40311.400967   38871.760400    5663.580500   
std     64332.856134   60797.155770   59554.107537   16563.280354   
min   -170000.000000  -81334.000000 -339603.000000       0.000000   
25%      2326.750000    1763.000000    1256.000000    1000.000000   
50%     19052.000000   18104.500000   17071.000000    2100.000000   
75%     54506.000000   50190.500000   49198.250000    5006.000000   
max    891586.000000  927171.000000  961664.000000  873552.000000   

           PAY_AMT2      PAY_AMT3       PAY_AMT4       PAY_AMT5  \
count  3.000000e+04   30000.00000   30000.000000   30000.000000   
mean   5.921163e+03    5225.68150    4826.076867    4799.387633   
std    2.304087e+04   17606.96147   15666.159744   15278.305679   
min    0.000000e+00       0.00000       0.000000       0.000000   
25%    8.330000e+02     390.00000     296.000000     252.500000   
50%    2.009000e+03    1800.00000    1500.000000    1500.000000   
75%    5.000000e+03    4505.00000    4013.250000    4031.500000   
max    1.684259e+06  896040.00000  621000.000000  426529.000000   

            PAY_AMT6  default.payment.next.month  
count   30000.000000                30000.000000  
mean     5215.502567                    0.221200  
std     17777.465775                    0.415062  
min         0.000000                    0.000000  
25%       117.750000                    0.000000  
50%      1500.000000                    0.000000  
75%      4000.000000                    0.000000  
max    528666.000000                    1.000000

In [13]:
X=data.copy(deep = True)
Y=data['default.payment.next.month']
X.drop(['ID','default.payment.next.month'], axis=1, inplace = True)

In [19]:
x_train,x_valid,y_train,y_valid = train_test_split(X, Y, test_size=0.33, random_state=42)

In [69]:
def scores(x_train, y_train, x_valid, y_valid):
    # model 
    model_RFC = RandomForestClassifier()
    model_LR = LogisticRegression()
    model_GBR = GradientBoostingClassifier()
    model_DTC = DecisionTreeClassifier()
    model_KN = KNeighborsClassifier()
    # fitting the model
    model_RFC.fit(x_train, y_train)
    model_LR.fit(x_train, y_train)
    model_GBR.fit(x_train, y_train)
    model_DTC.fit(x_train, y_train)
    model_KN.fit(x_train, y_train)
    # predict the model
    y_RFC=model_RFC.predict(x_valid)
    y_LR=model_LR.predict(x_valid)
    y_GBR=model_GBR.predict(x_valid)
    y_DTC=model_DTC.predict(x_valid)
    y_KN=model_KN.predict(x_valid)
    #score
    print("F1 Score")
    f1_RFC = f1_score(y_valid, y_RFC)
    f1_LR = f1_score(y_valid,y_LR)
    f1_GBR = f1_score(y_valid, y_GBR)
    f1_DTC = f1_score(y_valid,y_DTC)
    f1_KN = f1_score(y_valid,y_KN)
    print(("RFC : {}; LR : {}; GBR : {}; DTC : {}; KN : {}").format(f1_RFC,f1_LR,f1_GBR,f1_DTC,f1_KN))
    
    print("accuracy_score")
    f1_RFC = accuracy_score(y_valid, y_RFC)
    f1_LR = accuracy_score(y_valid,y_LR)
    f1_GBR = accuracy_score(y_valid, y_GBR)
    f1_DTC = accuracy_score(y_valid,y_DTC)
    f1_KN = accuracy_score(y_valid,y_KN)
    print(("RFC : {}; LR : {}; GBR : {}; DTC : {}; KN : {}").format(f1_RFC,f1_LR,f1_GBR,f1_DTC,f1_KN))

    print("precision_score")
    f1_RFC = precision_score(y_valid, y_RFC)
    f1_LR = precision_score(y_valid,y_LR)
    f1_GBR = precision_score(y_valid, y_GBR)
    f1_DTC = precision_score(y_valid,y_DTC)
    f1_KN = precision_score(y_valid,y_KN)
    print(("RFC : {}; LR : {}; GBR : {}; DTC : {}; KN : {}").format(f1_RFC,f1_LR,f1_GBR,f1_DTC,f1_KN))

    print("recall_score")
    f1_RFC = recall_score(y_valid, y_RFC)
    f1_LR = recall_score(y_valid,y_LR)
    f1_GBR = recall_score(y_valid, y_GBR)
    f1_DTC = recall_score(y_valid,y_DTC)
    f1_KN = recall_score(y_valid,y_KN)
    print(("RFC : {}; LR : {}; GBR : {}; DTC : {}; KN : {}").format(f1_RFC,f1_LR,f1_GBR,f1_DTC,f1_KN))
    
    print("precision_recall_curve")
    f1_RFC = precision_recall_curve(y_valid, y_RFC)
    f1_LR = precision_recall_curve(y_valid,y_LR)
    f1_GBR = precision_recall_curve(y_valid, y_GBR)
    f1_DTC = precision_recall_curve(y_valid,y_DTC)
    f1_KN = precision_recall_curve(y_valid,y_KN)
    print(("RFC :\n{}; LR :\n{}; GBR :\n{}; DTC :\n{}; KN :\n{}").format(f1_RFC,f1_LR,f1_GBR,f1_DTC,f1_KN))
    
    print("confusion_matrix")
    f1_RFC = confusion_matrix(y_valid, y_RFC)
    f1_LR = confusion_matrix(y_valid,y_LR)
    f1_GBR = confusion_matrix(y_valid, y_GBR)
    f1_DTC = confusion_matrix(y_valid,y_DTC)
    f1_KN = confusion_matrix(y_valid,y_KN)
    print(("RFC :\n{};\nLR :\n{};\nGBR :\n{};\nDTC :\n{};\nKN :\n{}").format(f1_RFC,f1_LR,f1_GBR,f1_DTC,f1_KN))

    #precision_recall_curve

In [70]:
scores(x_train, y_train, x_valid, y_valid)

F1 Score
RFC : 0.45719329214474846; LR : 0.0; GBR : 0.47108181000899013; DTC : 0.3985843839858439; KN : 0.23791821561338292
accuracy_score
RFC : 0.8136363636363636; LR : 0.7820202020202021; GBR : 0.8217171717171717; DTC : 0.7253535353535353; KN : 0.7515151515151515
precision_score
RFC : 0.6261079774375503; LR : 0.0; GBR : 0.6666666666666666; DTC : 0.381294964028777; KN : 0.35887850467289717
recall_score
RFC : 0.3600556070435589; LR : 0.0; GBR : 0.36422613531047265; DTC : 0.417516218721038; KN : 0.17794253938832252
precision_recall_curve
RFC :
(array([0.2179798 , 0.62610798, 1.        ]), array([1.        , 0.36005561, 0.        ]), array([0, 1], dtype=int64)); LR :
(array([0.2179798, 1.       ]), array([1., 0.]), array([0], dtype=int64)); GBR :
(array([0.2179798 , 0.66666667, 1.        ]), array([1.        , 0.36422614, 0.        ]), array([0, 1], dtype=int64)); DTC :
(array([0.2179798 , 0.38129496, 1.        ]), array([1.        , 0.41751622, 0.        ]), array([0, 1], dtype=int64));

In [62]:
# model 
model_RFC = RandomForestClassifier()
model_LR = LogisticRegression()
model_GBR = GradientBoostingClassifier()
model_DTC = DecisionTreeClassifier()
model_KN = KNeighborsClassifier()
# fitting the model
model_RFC.fit(x_train, y_train)
model_LR.fit(x_train, y_train)
model_GBR.fit(x_train, y_train)
model_DTC.fit(x_train, y_train)
model_KN.fit(x_train, y_train)

# predict the model
y_RFC=model_RFC.predict(x_valid)
y_LR=model_LR.predict(x_valid)
y_GBR=model_LR.predict(x_valid)
y_DTC=model_LR.predict(x_valid)
y_KN=model_LR.predict(x_valid)

In [55]:
model_LR.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
#plt.figure(figsize=(14,7))
#plt.title("Average Arrival Delay for Each Airline, by Month")
#sns.heatmap(data=X, annot=True)